name: data-science-handbook
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
