name: data-science-handbook-35
channels:
  - defaults
dependencies:
  - python=3.5
  - pip
  - numpy=1.11.1
  - pandas=0.18.1
  - scipy=0.17.1
  - scikit-learn=0.17.1
  - scikit-image=0.12.3
  - pillow=3.4.2
  - seaborn=0.7
  - jupyter
  - notebook
  - line_profiler
  - memory_profiler
  - numexpr
  - pandas-datareader
  - netcdf4
  - pip:
    - matplotlib==1.5.1
